[project]
name = "pobi-eval"
dynamic = ["version"]
description = "Evaluation package."
readme = "README.md"
authors = [
    { name = "Yassine Bargach", email = "yassine@straylabs.ai" }
]
requires-python = ">=3.10"
dependencies = [
]

[project.scripts]
pobi_eval = "pobi_eval:eval"

[tool.hatch.build.targets.wheel]
packages = ["src/pobi_eval"]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"
